FROM anaccentos:1.0
MAINTAINER CVUSK


WORKDIR /opt/
# BE SURE to change NotebookApp.token variable to your password
RUN jupyter notebook --generate-config  --allow-root && \
    ipython profile create
RUN echo "c.NotebookApp.ip = '*'" >>/root/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.open_browser = False" >>/root/.jupyter/jupyter_notebook_config.py && \
    echo "c.InteractiveShellApp.matplotlib = 'inline'" >>/root/.ipython/profile_default/ipython_config.py


RUN mkdir -p /opt/files/python
WORKDIR /opt/files/python/
RUN echo 'nohup jupyter notebook --allow-root &' >> /opt/files/python/run_jupyter.sh

WORKDIR /opt/

EXPOSE 8888
