FROM anaccentos:1.1
MAINTAINER CVUSK


WORKDIR /opt/
# BE SURE to change NotebookApp.token variable to your password
RUN jupyter notebook --generate-config  --allow-root && \
    ipython profile create
RUN echo "c.NotebookApp.ip = '*'" >>/root/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.open_browser = False" >>/root/.jupyter/jupyter_notebook_config.py && \
    echo "c.InteractiveShellApp.matplotlib = 'inline'" >>/root/.ipython/profile_default/ipython_config.py

RUN mkdir -p /opt/sanickube/shdir
RUN echo 'nohup jupyter notebook --allow-root &' >> /opt/sanickube/shdir/run_jupyter.sh

WORKDIR /opt/sanickube/shdir/

EXPOSE 8888
