FROM basecentos:1.2
MAINTAINER CVUSK


WORKDIR /opt/
RUN wget https://repo.continuum.io/archive/Anaconda3-4.2.0-Linux-x86_64.sh
RUN bash Anaconda3-4.2.0-Linux-x86_64.sh -b -p /opt/anaconda3
ENV PATH="/opt/anaconda3/bin:$PATH"
RUN conda install -c http://conda.binstar.org/menpo opencv
RUN conda create -n py27 python=2.7 anaconda
RUN source activate py27
RUN conda install notebook ipykernel
RUN ipython kernel install --user
RUN conda install -c http://conda.binstar.org/menpo opencv
RUN source deactivate
RUN ipython kernel install --user

# pip install python libraries
RUN pip install --upgrade pip

WORKDIR /opt/
RUN rm -f Anaconda3-4.2.0-Linux-x86_64.sh
